# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'PizzaTime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PizzaTime
	pod 'Easy'
	pod 'ImageViewer'
	pod 'Alamofire'
	pod 'AFNetworking'
	pod 'AlamofireImage'
	pod 'SwiftyJSON'
	pod 'PullToRefreshKit'
#	pod 'Nuke'

  target 'PizzaTimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
